title: GamaPlatform
email: your-email@domain.com
description: Gama Test Version
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://dphilippon.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: gama
github_username:  dphilippon

# Build settings
encoding: utf-8
markdown: redcarpet
highlighter: rouge
theme: minima
menu:
include: ['_wiki/WikiOnly']
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
redcarpet:
    extensions: ["no_intra_emphasis", "tables", "autolink", "strikethrough", "with_toc_data"]
wikiToJekyll:
    user_name: gama-platform
    repository_name: gama
    deploy_remote: "origin"
    deploy_branch: "master"
    wiki_repository_url: "https://github.com/gama-platform/gama.wiki.git"
    wiki_source: "_wiki"
    wiki_dest: "wiki"
    commit_and_push: false